### PR TITLE
Fix paused website

### LINKED ISSUE #1393: Third-party requests are blocked by Ghostery extension when they are fetched by a service worker.
## Description

Third-party requests are blocked by Ghostery extension when they are fetched by a service worker.

## Steps to Reproduce

1. Connect to [`https://fabulous-voice-74.app.baqend.com/Ghostery/`](https://fabulous-voice-74.app.baqend.com/Ghostery/)
2. Reload the page to make sure the service worker is active.
3. Activate Ghostery.
4. Select `Trust Site` from Ghostery’s UI
5. Open dev tools and navigate to the network tab.
6. Reload the page to see the failed requests (https://bat.bing.com/bat.js) in the network tab.

## Expected result:

The request should not be blocked.

## Reproduces how often:

Always

## Other Additional Information:

- Does the issue resolve itself when disabling Ghostery? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

Everything works already if the Ad-blocking option is turned off

### PR DESCRIPTION
**Pull request by smalluban**
Fixes #1393 

* In v8 we must add a check in the webRequestPipline events if the origin is added to the trusted sites
* In v10 on chromium the rule with `allowAllRequests` is not sufficient, but still needed. Only with two (original one, and another added) almost all of the requests pass through

If merging, please use rebase option. I separated changes for v8 and v10 in two commits.

### CODE REVIEW

File: extension-manifest-v2/src/background.js [hunk 1]
```diff
@@ -1018,6 +1018,18 @@ function initializeDispatcher() {
 		common.modules.core.action('refreshAppState');
 	});
 }
+/**
+ * Checks if the origin of the request comes from whitelisted sites
+ * @param {webRequestPipeline.request} state
+ * @returns boolean
+ */
+function isOriginWhitelisted(state) {
```
Comment (chrmod) [inline extension-manifest-v2/src/background.js:1026]: this is already provided by `Policy.getSitePolicy`

**Review by chrmod — DISMISSED** [review]

**Comment by philipp-classen** [comment]
Tests are failing, but it seems unrelated to the changes:

```
npm ERR! Downloading "dnr-ads-2"...
npm ERR! Generated 85347 rules
npm ERR! file:///home/runner/work/ghostery-extension/ghostery-extension/extension-manifest-v3/scripts/download-engines/utils.js:117
npm ERR!         throw new Error('Too many DNR rules');
npm ERR!               ^
npm ERR! 
npm ERR! Error: Too many DNR rules
npm ERR!     at Object.close (file:///home/runner/work/ghostery-extension/ghostery-extension/extension-manifest-v3/scripts/download-engines/utils.js:117:15)
npm ERR!     at file:///home/runner/work/ghostery-extension/ghostery-extension/extension-manifest-v3/scripts/download-engines/index.js:143:12
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Review by chrmod — APPROVED** [review]
