### PR TITLE
Fix long node modules paths in the dist build

### LINKED ISSUE #1723: Windows: file path limit exceeded
On some security configurations of Windows the file path is limited to 256 character. In this scenarios, Ghostery extension may fail to load if it is installed in a profile that's path is already relatively long.

Here is a list of longest file paths:
```
127 ./node_modules/@whotracksme/webextension-packages/packages/reporting/src/request/steps/token-telemetry/cached-entry-pipeline.js
120 ./node_modules/@whotracksme/webextension-packages/packages/reporting/src/request/steps/token-telemetry/token-pipeline.js
118 ./node_modules/@whotracksme/webextension-packages/packages/reporting/src/request/steps/token-telemetry/key-pipeline.js
116 ./node_modules/@whotracksme/webextension-packages/packages/reporting/src/request/steps/token-checker/token-domain.js
116 ./node_modules/@whotracksme/webextension-packages/packages/anonymous-communication/src/server-public-key-accessor.js
114 ./node_modules/@whotracksme/webextension-packages/packages/reporting/src/webrequest-pipeline/webrequest-context.js
```
It looks like the Anti-Tracking codebase is the culprit. 

This issue is related to Ghostery 10 rollup and contributes to the list of problems listed in #1669

### PR DESCRIPTION
**Pull request by smalluban**
Fixes #1723

* Renames `node_modules` to `npm` in the dist
* Adds a rule to throw if the dist path to file exceed 100 characters
* Cleans up not needed patches

### CODE REVIEW

File: extension-manifest-v3/scripts/build.js [hunk 1]
```diff
@@ -285,6 +280,19 @@ const buildPromise = build({
         minifyInternalExports: false,
         entryFileNames: '[name].js',
         assetFileNames: 'assets/[name].[ext]',
+        sanitizeFileName: (name) => {
+          name = name
+            .replace(/[\x00?*]+/g, '_') // eslint-disable-line no-control-regex
```
Comment (smalluban) [inline extension-manifest-v3/scripts/build.js:285]: This is taken from the default behavior:
https://rollupjs.org/configuration-options/#output-sanitizefilename

**Review by chrmod — APPROVED** [review]
