### PR TITLE
Fix source url check for updating stats on Firefox

### LINKED ISSUE #1423: The panel doesn't display blocked or modified trackers
**Description:**
The Ghostery panel doesn't show blocked and/or modified trackers when a website is first accessed. When the website is reloaded, the panel shows the number of blocked and/or modified trackers.

**Steps to Reproduce:**
1. Open Ghostery Private Browser
2. Open website, for example https://www.wowhead.com/
3. Open Ghostery panel
image
4. Reload the website
5. Open Ghostery panel
image

**Expected Results:**

**Versions:**

	Browser: Ghostery Private Browser 2023.9 (#3e8eed2)
	OS: Android 14
	GBE 10.2.2

	Browser: Ghostery Private Browser 2023.9 (#3e8eed2)
	OS: Android 11
	GBE 10.2.2

### PR DESCRIPTION
**Pull request by smalluban**
Fixes #1423 

On Firefox when you type the URL by hand and navigate, for example, `onet.pl` - the browser navigates at first to `http://onet.pl`, which is saved as the URL of the tab (when stats are initialized). However, the final address is `https://www.onet.pl`. It has not only a different protocol, but also a subdomain added. 

When requests are checked after that navigation, the `request.isFromSourceUrl()` returns false, as those requests have the final URL as the source. After reloading the page, the `stats.url` is set to correct value, as the tab is already at the "final" URL.

~~This PR fixes the issue by loosening the condition, to check if the origin (domain or hostname) is a part of the source URL (ancestors, initiator, or sourceUrl). I am aware that this is not 100% correct, as the pathname or query might contain the domain, but in this case, this is just a protection to not pass through requests from the "previous page" navigation - which is very unlikely to happen. Even using parsed URLs might not be sufficient, as the case with added subdomains would fail (like the example of `onet.pl` -> `www.onet.pl`).~~

EDIT:

The final solution chooses a URL to check, parses it, and then compares the domain or hostname. It should now be 100% complaint. 

The URL comes from a different part of the original request, so it is not parsed before, we have to do it within the function.

### CODE REVIEW

**Comment by smalluban** [comment]
@philipp-classen Please review this PR, @chrmod had some doubts about loosening the condition, but truthfully I cannot find another working solution.

File: extension-manifest-v3/src/background/utils/request.js [hunk 1]
```diff
@@ -53,17 +53,17 @@ export default class ExtendedRequest extends Request {
...
     /* Firefox APIs */
 
     if (frameAncestors && frameAncestors.length > 0) {
-      return url === frameAncestors[frameAncestors.length - 1].url;
+      return frameAncestors[frameAncestors.length - 1].url?.includes(origin);
     }
 
     if (this.sourceUrl) {
-      return url === this.sourceUrl;
+      return this.sourceUrl.includes(origin);
```
Comment (philipp-classen) [inline extension-manifest-v3/src/background/utils/request.js:66]: Would `startsWith` be still correct (and more precise)?

Comment (smalluban) [reply extension-manifest-v3/src/background/utils/request.js:66]: Sadly nope, I even gave an example in the description, which was a case where the bug was found. The sourceUrl is `https://www.onet.pl`, but the `url` from the original code was `http://onet.pl` (where we saved it as `onet.pl`). This is way we cannot compare full URLs as they are different (in case of Firefox, where it dispatch an navigation event even for the redirect).

**Review by chrmod — CHANGES_REQUESTED** [review]
How about we compare eTLD+1 instead?

**Comment by smalluban** [comment]
> How about we compare eTLD+1 instead?

No idea what you mean, does it return `true` for a pair of `http://onet.pl` and `https://www.onet.pl` (mind a different protocol and subdomain)?

**Comment by chrmod** [comment]
yes, effective top level domain for those two urls is the same - `onet.pl`.

**Comment by chrmod** [comment]
you can use `tldts` or `cliqz/fast-url-parser`

File: extension-manifest-v3/src/background/utils/request.js [hunk 2]
```diff
@@ -53,27 +53,31 @@ export default class ExtendedRequest extends Request {
...
-    /* Chrome APIs */
-
-    const { frameType, initiator } = this._originalRequestDetails;
-
-    // For frameType 'sub_frame', we can't determine the origin URL
-    // as it might be the iframe itself or any of its ancestors
-    if (frameType === 'outermost_frame' && initiator) {
-      return url.startsWith(initiator);
+    if (url) {
+      const parsedUrl = parse(url);
```
Comment (chrmod) [inline extension-manifest-v3/src/background/utils/request.js:79]: we will likely parse the same URL over and over again. One way to do it would be to add some in-memory cache. This is what we did in V8 - https://github.com/ghostery/common/blob/main/modules/core/sources/LRU.ts

**Review by chrmod — APPROVED** [review]
