### PR TITLE
MV2: prevent tracker stats leakage between visits

### LINKED ISSUE #1241: Observed trackers "leak" between page loads
**Description**
Tracker is visible on second website when I go to it strictly from the search engine website. After reloads, tracker disappears.

**Steps to Reproduce Scenario 1**
1. Open any search engine website, for example https://google.com
2. Open Devtools and switch to Network tab
3. Search for example example.com
4. Open Ghostery panel and look for Site Analytics/ Google Beacons. 
5. Copy "www.google.com/gen_204"
6. Search it in Network tab, from step 2
image

7. Open [Example Domain](https://example.com/) and open Ghostery panel
image

8. **Tracker is still visible.**
9. Reload the website and open again Ghostery panel
image

---

**Steps to Reproduce Scenario 2**
1. Open any search engine website, for example https://bing.com
2. Open Devtools and switch to Network tab
3. Search for example happy bab la
4. Open Ghostery panel and look for Advertising/ Bing Ads 
5. Copy "bing.com"
6. Search it in Network tab, from step 2
image

7. Open [HAPPY - Tłumaczenie na polski - bab.la](https://pl.bab.la/slownik/angielski-polski/happy) and open Ghostery panel
image

8. **Tracker is still visible.**
9. Reload the website and open again Ghostery panel
image

**Expected results**
Tracker cannot be visible on second website when I go to it strictly from the search engine website. 

**Versions**
Browser: Chrome 115.0.5790.99 (Official Build) (64-bit)
OS: Windows 10 Pro 19045.3086
GBE: 8.11.1

### PR DESCRIPTION
**Pull request by chrmod**
This PR fixes a a common bug that Google Beacons were reported on websites navigated from google.com.

fix #1241

### CODE REVIEW

File: extension-manifest-v2/src/classes/EventHandlers.js [hunk 1]
```diff
@@ -331,6 +331,9 @@ class EventHandlers {
 		// process the tracker asynchronously
 		// very important to block request processing as little as necessary
 		setTimeout(() => {
+			if (tabInfo.getTabInfo(tab_id, 'url') !== eventMutable.tabUrl) {
```
Comment (philipp-classen) [inline extension-manifest-v2/src/classes/EventHandlers.js:334]: As I understand, this relies on the adblocker engine to handle the requests later?

For instance, beacon requests like this will be skipped:
```
"https://www.google.com/gen_204?atyp=i&bb=1&ei=vQotZb6tM4WE9u8P16-k2As&ct=slh&v=t1&im=M&m=HV&pv=0.765146168780363&me=1:1697450714401,x:0,V,0,0,704,1059:0,N,1,vQotZb6tM4WE9u8P16-k2As:0,R,1,101,24,36,92,33:0,R,1,CAgQAA,24,88,764,40:0,R,1,CAwQAQ,24,88,73,40:0,R,1,CAcQAQ,103,88,66,40:0,R,1,CAkQAQ,175,88,65,40:0,R,1,CAsQAQ,246,88,75,40:0,R,1,CEsQAQ,327,88,64,40:0,R,1,CEwQAQ,397,88,64,40:0,R,1,CE0QAQ,467,88,86,40:0,R,1,CAQQGA,28,269,652,1904:0,R,1,CBoQAA,28,269,600,117:0,R,1,CBwQAA,28,416,600,117:0,R,1,CA4QAA,28,577,652,150:0,R,1,CA8QAQ,28,614,652,48:0,R,1,CBMQAQ,28,663,652,48:0,R,1,CB0QAA,28,771,600,117:0,R,1,CC0QAA,28,917,600,117:483,h,1,CBoQAA,o:1,h,1,CAQQGA,o:65,B,2601:535,h,1,CBMQAQ,i:0,h,1,CA4QAA,i:0,h,1,CAQQGA,i:118,h,1,CBMQAQ,o:0,h,1,CA8QAQ,i:66,h,1,CA8QAQ,o:17,h,1,CA4QAA,o:33,h,1,CBwQAA,i:620,G,1,CBwQAA,164,58,1:0,c,192,474:0,G,1,CBwQAA,164,58:0,G,1,CAQQGA,164,205:11,e,C&zx=1697450716351&opi=89978449" 
```

Comment (chrmod) [reply extension-manifest-v2/src/classes/EventHandlers.js:334]: `_processBug` is reporting only, does not relate to the action of blocking

Comment (chrmod) [reply extension-manifest-v2/src/classes/EventHandlers.js:334]: and yes, the goal is to ignore the beacons on subsequent page load

**Review by philipp-classen — APPROVED** [review]
